const NUMBER_OF_WINNER = 22;
const PRESENT_REQUEST_COUNTER_FIELD = 'counterField';
const PRESENT_REQUEST_COUNTER_VALUE = 'counterValue';

module.exports = {
  NUMBER_OF_WINNER,
  PRESENT_REQUEST_COUNTER_FIELD,
  PRESENT_REQUEST_COUNTER_VALUE,
};
